### ISSUE TITLE
Add feature for user to upload the excel file that contain the player

### ISSUE THREAD

**Issue by relieyanhilman** [relieyanhilman/badminhub#18]
Menambahkan interface upload excel yang berisi pemain di dashboard

**Comment by relieyanhilman** [comment]
Sudah ditambahkan fitur import player di halaman 'dashboard' dan 'player list'. Berikut cuplikan gambar fitur ini.
[https://drive.google.com/file/d/1UpC8p6MP-dKyDZYmrQ-6CGcsdRNYI_Mb/view?usp=drive_link](url)
[https://drive.google.com/file/d/1UwZB2RANvDestvzqWpyx9mNOhZ6Sb0t8/view?usp=drive_link](url)
[https://drive.google.com/file/d/1UxKURPd8YbDF8dJrcJLlmCd4ySlO_WEw/view?usp=drive_link](url)

**Comment by eggidwitama** [comment]
untuk proses import player sudah oke namun perlu ditambahkan link untuk donwload default template file import player untuk memastikan user mengupload file yang sesuai, baik type file, susunan kolom, dll

Berikut saran revisi UI untuk halaman dashboard:
[https://drive.google.com/file/d/1nCwy4PNRhhJ_AKH6BBLwsAXesmMsXJid/view?usp=sharing](https://drive.google.com/file/d/1nCwy4PNRhhJ_AKH6BBLwsAXesmMsXJid/view?usp=sharing)
Bisa disesuaikan lagi, pointnya terdapat tautan untuk download template file import player agar user mengisi data player yang sudah sesuai dengan format yg telah ditentukan

**Comment by relieyanhilman** [comment]
Sudah ditambahkan template file untuk _import player_ di bagian bawah tombol import player. Berikut tautan terhadap cuplikan gambarnya
![Image](https://github.com/user-attachments/assets/77bd0197-a63b-4f9b-a0c1-ca05c5671488)

**Comment by eggidwitama** [comment]
Nice. Issue ini sudah bisa di-close
